### ISSUE TITLE
List registration methods

### ISSUE THREAD

**Issue by ebrahimebrahim** [brain-microstructure-exploration-tools/abcd-registration-experiments#14]
list pairwise registration methods that we will evaluate

- ants FA
- voxelmorph
- ...

**Comment by jamesfishbaugh** [comment]
After giving it some thought, I think these are the main methods we should evaluate:

- ANTs FA
- Voxelmorph FA
- DMMReg
- DTITK
- mrregister FODs

This covers the 3 main registration types (scalar, tensor, fod) and includes the most popular packages we would be expected to compare against. After thinking about it, I would hesitate to compare with any previous version of Hasting's research since it will have a very similar formulation to "ours". It also seems a bit redundant since it would be the same flavor as evaluating voxelmorph as both models were not trained explicitly for dwi.

**Comment by ebrahimebrahim** [comment]
Great list, and I very much agree with why you pared it down to this set of methods!

**Comment by ebrahimebrahim** [comment]
The inputs we need to prepare in order to run these evaluations are
- FA
- DTI
- FODs
- TOMs
